myyntitekstit = [
"\rPelipäivä bitses! :-DD \rHypätkääs odottamaan pelejä tuttuun ja turvalliseen tuksustaniaan! \rhttps://www.popflash.site/scrim/tuksustania",
"\rSITÄ PELIÄ! \rhttps://www.popflash.site/scrim/tuksustania",
"Let plei cee äs! wii hääv a jono at tuksustaniassa\rhttps://www.popflash.site/scrim/tuksustania",
"Onko pelureita? :hamster:\rhttps://www.popflash.site/scrim/tuksustania",
"Hyvän viban cs pelejä tyyliin nyt? Niksuttelu kielletty ofc \rhttps://www.popflash.site/scrim/tuksustania",
"omae wa mou pelideiru \rhttps://www.popflash.site/scrim/tuksustania",
"Pelipäivä on juhlapäivä - Timo Jutila\rhttps://www.popflash.site/scrim/tuksustania",
"Laatuaikaa kavereiden kanssa, vai huutoa ja riitelyä runkkareita vastaan? click the link and find out!\rhttps://www.popflash.site/scrim/tuksustania",
"Kuitenki haluat pelata\rhttps://www.popflash.site/scrim/tuksustania",
"\rhttps://www.popflash.site/scrim/tuksustania",
"HIP HEI HUORAT, ON MEILLÄ KYRVÄT SUORAT! :\'D \rhttps://www.popflash.site/scrim/tuksustania",
"UwU!! YAMETEEEEE\rhttps://www.popflash.site/scrim/tuksustania",
"esl pro tour katowice hakee pelureita osoitteessa https://www.popflash.site/scrim/tuksustania",
"do juu want tu leikki? https://www.popflash.site/scrim/tuksustania",
"Olisiko se pelihommels? https://www.popflash.site/scrim/tuksustania",
"etsitään osujia ja hosujia tositarkoituksella! https://www.popflash.site/scrim/tuksustania",
]