myyntitekstit = [
"\rPelipäivä bitses! :-DD \rHypätkääs odottamaan pelejä tuttuun ja turvalliseen tuksustaniaan! \rhttps://popflash.site/-/1/scrim",
"\rSITÄ PELIÄ! \rhttps://popflash.site/-/1/scrim",
"Let plei cee äs! wii hääv a jono at tuksustaniassa\rhttps://popflash.site/-/1/scrim",
"Onko pelureita? :hamster:\rhttps://popflash.site/-/1/scrim",
"Hyvän viban cs pelejä tyyliin nyt? Niksuttelu kielletty ofc \rhttps://popflash.site/-/1/scrim",
"omae wa mou pelideiru \rhttps://popflash.site/-/1/scrim",
"Pelipäivä on juhlapäivä - Timo Jutila\rhttps://popflash.site/-/1/scrim",
"Laatuaikaa kavereiden kanssa, vai huutoa ja riitelyä runkkareita vastaan? click the link and find out!\rhttps://popflash.site/-/1/scrim",
"Kuitenki haluat pelata\rhttps://popflash.site/-/1/scrim",
"\rhttps://www.popflash.site/scrim/tuksustania",
"HIP HEI HUORAT, ON MEILLÄ KYRVÄT SUORAT! :\'D \rhttps://popflash.site/-/1/scrim",
"UwU!! YAMETEEEEE\rhttps://www.popflash.site/scrim/tuksustania",
"esl pro tour katowice hakee pelureita osoitteessa https://popflash.site/-/1/scrim",
"do juu want tu leikki? https://popflash.site/-/1/scrim",
"Olisiko se pelihommels? https://popflash.site/-/1/scrim",
"etsitään osujia ja hosujia tositarkoituksella! https://popflash.site/-/1/scrim",
]
