myyntitekstit = [
"\rPelipäivä bitses! :-DD \rHypätkääs odottamaan pelejä tuttuun ja turvalliseen tuksustaniaan! \rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"\rSITÄ PELIÄ! \rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"Let plei cee äs! wii hääv a jono at tuksustaniassa\rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"Onko pelureita? :hamster:\rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"Hyvän viban cs pelejä tyyliin nyt? Niksuttelu kielletty ofc \rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"omae wa mou pelideiru \rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"Pelipäivä on juhlapäivä - Timo Jutila\rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"Laatuaikaa kavereiden kanssa, vai huutoa ja riitelyä runkkareita vastaan? click the link and find out!\rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"Kuitenki haluat pelata\rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"\rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"HIP HEI HUORAT, ON MEILLÄ KYRVÄT SUORAT! :\'D \rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"UwU!! YAMETEEEEE\rhttps://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"esl pro tour katowice hakee pelureita osoitteessa https://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"do juu want tu leikki? https://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"Olisiko se pelihommels? https://popflash.site/-/jorgen-j-jonsson-938288/scrim",
"etsitään osujia ja hosujia tositarkoituksella! https://popflash.site/-/jorgen-j-jonsson-938288/scrim",
]
